[build]
  command = "pnpm build"
  publish = "public"
  functions = "functions"
  node_version = "18.20.3"

[[redirects]]
  from = "/redirect.php"
  to = "/.netlify/functions/redirect"
  status = 301
  force = true
