[build]
  command = "pnpm install && pnpm run build"
  publish = "dist"
  functions = "functions"



[[redirects]]
  from = "/redirect.php"
  to = "/.netlify/functions/redirect"
  status = 301
  force = true
